os: linux
dist: xenial
sudo: required
language: python
cache: pip

python:
  - '3.7'

install:
  - PIPENV_HIDE_EMOJIS=true PIPENV_COLORBLIND=true PIPENV_NOSPIN=true make install

script:
  - make test
  - make lint
  - make mypy
  - make check-dist

after_success:
  - ls -lha
  - bash <(curl -s https://codecov.io/bash)

stages:
  - name: test
  #  if: type = pull_request OR branch = master OR tag IS present
  - name: build
#    if: type = push AND (branch = master OR tag IS present)

jobs:
  include:
    - stage: test
      python: 3.7
      name: 'Python: 3.7'
      script:
        - make test
    - stage: build
      name: 'PyPI Build and Upload'
      python: 3.7
      services:
        - docker
      install: skip
      env:
        - 'PIP=pip'
        - 'CIBW_TEST_REQUIRES=pytest'
        - 'CIBW_TEST_COMMAND="pytest {project}/tests"'
      script:
        - pip install -U wheel
        - python setup.py sdist bdist_wheel
      after_success:
        - ls -lha dist
      deploy:
        provider: pypi
        skip_cleanup: true
        user: i8enn
        password:
          secure: 'pypi-AgEIcHlwaS5vcmcCJGY4NDI5MTJiLTJmZTItNDM5ZS05MTMyLWI5ZDZlMTNmMzUwZQACPXsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJweWRhbnRpYy1vZG0iXX0sICJ2ZXJzaW9uIjogMX0AAAYg369ZMQZaGQ6qpqY2SXjsAhOUlbTYvo-fihW59qZfQ-Q'
        on:
          tags: true
          all_branches: true
