os: linux
dist: xenial
language: python
cache: pip
python:
- '3.7'
install:
- PIPENV_HIDE_EMOJIS=true PIPENV_COLORBLIND=true PIPENV_NOSPIN=true make install
script:
- make test
- make lint
- make mypy
- make check-dist
after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)
stages:
- name: test
  if: type = pull_request OR branch = master OR tag IS present
- name: build
  if: type = push AND (branch = master OR tag IS present)
jobs:
  include:
  - stage: test
    python: 3.7
    name: 'Python: 3.7'
    before_script:
    - docker-compose up -d
    script:
    - make test
    after_script:
    - docker-compose down
  - stage: build
    name: PyPI Build and Upload
    python: 3.7
    services:
    - docker
    install: skip
    env:
    - PIP=pip
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}/tests"
    before_script:
    - pip install -U wheel
    - make clean
    script:
    - python setup.py sdist bdist_wheel
    after_success:
    - ls -lha dist
    deploy:
      provider: pypi
      skip_existing: true
      username: '__token__'
      password:
        secure: erJmYEBtLO9F+MOZaeUK/WBxnVqoc7Vnjxjx5oK07n6qRu4pOJrqg2d+vmIYuXUK+U1NhLVnQl+fg84LREj/oJbTx7ArU+FIn1CrDVWV9wO8eashnNPFemuagUbEaUFsJalcYOOxE/KJ8NuOIgJuSzK/KDchHmG8+xYLnrFmqm0fN0t3X6skFrN6I2LdZBwjizEcOeLdNnJM5PIdVA8sDHD2lTCueGO+2QxkPvvTn0x/W7nuEyWEDiwL8TEtAchbrGRFo6yvskgWFaQAdgmoF+ejWJkn21oPTsFlgiq84ikvryKFrNXj9477MtcpkyNGpPpIArEAQils/QpSYKOD82MiUjl7JB+od3qb7VkVCFnIQAocyUjAk3UZ3/kJDf8ahXM7LY9bufWpZia0z3PZSkZ38OBSXq/ppOLUhxq7pw41rr4DZjB7Jo6u8l0E1KdvNVLwHTTkv9xx4gzASPM+P8eQku8uP/c5WJczy9D2g6Fld5/WioTpkpNNgk7tRyGb/pl4rmU+Dn4kIY2++1VgYZyT0W0PGM+nJpr06RWuEjvVc4V7DWC6vObXK0IXiUo8UYLfJ5JQmPgOH4LgNSoCAMe77nXgTmtM5D0EFkEQYBgKLOi6AIQe0RmEnWzjbRqJE9u856h/gpjC2kGoD/NYiUQovfh7LxGaKe8pUHdojQM=
      on:
        tags: true